# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\8-Project\Python-Project\1-PyQt\4-QVideoWidget\git-player\pyqt-qmediaplayer\src\MediaPlayer\MediaPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(866, 556)
        Form.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(640, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_player = QtWidgets.QFrame(self.frame_2)
        self.frame_player.setMinimumSize(QtCore.QSize(640, 480))
        self.frame_player.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_player.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_player.setLineWidth(0)
        self.frame_player.setObjectName("frame_player")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_player)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layout_videoframe = QtWidgets.QHBoxLayout()
        self.layout_videoframe.setSpacing(0)
        self.layout_videoframe.setObjectName("layout_videoframe")
        self.horizontalLayout_3.addLayout(self.layout_videoframe)
        self.verticalLayout.addWidget(self.frame_player)
        self.frame_tools = QtWidgets.QFrame(self.frame_2)
        self.frame_tools.setMinimumSize(QtCore.QSize(640, 48))
        self.frame_tools.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_tools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tools.setLineWidth(0)
        self.frame_tools.setObjectName("frame_tools")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_tools)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_befor = QtWidgets.QPushButton(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_befor.sizePolicy().hasHeightForWidth())
        self.pushButton_befor.setSizePolicy(sizePolicy)
        self.pushButton_befor.setObjectName("pushButton_befor")
        self.horizontalLayout_2.addWidget(self.pushButton_befor)
        self.pushButton_play = QtWidgets.QPushButton(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_play.sizePolicy().hasHeightForWidth())
        self.pushButton_play.setSizePolicy(sizePolicy)
        self.pushButton_play.setStyleSheet("")
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout_2.addWidget(self.pushButton_play)
        self.pushButton_next = QtWidgets.QPushButton(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next.sizePolicy().hasHeightForWidth())
        self.pushButton_next.setSizePolicy(sizePolicy)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_2.addWidget(self.pushButton_next)
        self.lcdNumber_progress = QtWidgets.QLCDNumber(self.frame_tools)
        self.lcdNumber_progress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_progress.setLineWidth(1)
        self.lcdNumber_progress.setObjectName("lcdNumber_progress")
        self.horizontalLayout_2.addWidget(self.lcdNumber_progress)
        self.pushButton_audio = QtWidgets.QPushButton(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_audio.sizePolicy().hasHeightForWidth())
        self.pushButton_audio.setSizePolicy(sizePolicy)
        self.pushButton_audio.setObjectName("pushButton_audio")
        self.horizontalLayout_2.addWidget(self.pushButton_audio)
        self.pushButton_file = QtWidgets.QPushButton(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_file.sizePolicy().hasHeightForWidth())
        self.pushButton_file.setSizePolicy(sizePolicy)
        self.pushButton_file.setObjectName("pushButton_file")
        self.horizontalLayout_2.addWidget(self.pushButton_file)
        self.pushButton_setup = QtWidgets.QPushButton(self.frame_tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setup.sizePolicy().hasHeightForWidth())
        self.pushButton_setup.setSizePolicy(sizePolicy)
        self.pushButton_setup.setObjectName("pushButton_setup")
        self.horizontalLayout_2.addWidget(self.pushButton_setup)
        self.verticalLayout.addWidget(self.frame_tools)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_list = QtWidgets.QFrame(self.frame)
        self.frame_list.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list.setLineWidth(0)
        self.frame_list.setObjectName("frame_list")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_list)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_playlist = QtWidgets.QListWidget(self.frame_list)
        self.listWidget_playlist.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_playlist.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_playlist.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_playlist.setObjectName("listWidget_playlist")
        self.horizontalLayout_4.addWidget(self.listWidget_playlist)
        self.horizontalLayout.addWidget(self.frame_list)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_befor.setText(_translate("Form", "上一个"))
        self.pushButton_play.setText(_translate("Form", "播放"))
        self.pushButton_next.setText(_translate("Form", "下一个"))
        self.pushButton_audio.setText(_translate("Form", "声音"))
        self.pushButton_file.setText(_translate("Form", "文件"))
        self.pushButton_setup.setText(_translate("Form", "设置"))


